version: '3.9'
services:
  backend:
    image: alinbal/trifork:employeebackend
    depends_on:
      triforkdb:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - '8080:8080'
  triforkdb:
    image: postgres:latest
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql